[package]
name = "scparcer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6"
rand = "0.8" 
colored = "2.1.0"